## defaults for _all_ profiles
[default]
address = "0.0.0.0"
limits = { form = "64 kB", json = "1 MiB" }

[global]
port = 8545

## set only when compiled in debug mode, i.e, `cargo build`
[debug]

## set only when compiled cin release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]